/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yan Kaic
 */
public class Simulation extends javax.swing.JFrame {

  private Node incompleteNode;
  private Edge incompleteEdge;
  private ArrayList<Node> nodes;
  private MouseAdapter nodeMouseClicked;

  /**
   * Creates new form Simulation
   */
  public Simulation() {
    initComponents();

    init();

  }

  private void init() {
    nodePanel.addMouseMotionListener(new MouseAdapter() {
      @Override
      public void mouseMoved(MouseEvent e) {
        if (incompleteNode != null) {
          incompleteNode.moveMouse();
        }
      }
    }
    );
    nodes = new ArrayList<>();

    this.addKeyListener(new KeyAdapter() {
      @Override
      public void keyTyped(KeyEvent e) {
        if (incompleteNode != null) {
          nodePanel.remove(incompleteNode);
          incompleteNode = null;
          repaint();
        }
      }
    }
    );

    nodeMouseClicked = new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        nodes.add(incompleteNode);
        incompleteNode.removeMouseListener(nodeMouseClicked);
        incompleteNode.createRouter();
        incompleteNode = null;
      }
    };

    refresh();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    addNodeButton = new javax.swing.JButton();
    addEdgeButton = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    jScrollPane1 = new javax.swing.JScrollPane();
    nodePanel = new javax.swing.JPanel(){
      @Override
      public void paintComponent(Graphics gph) {
        super.paintComponent(gph);
        Graphics2D graphics = (Graphics2D) gph.create();
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        paintNodePanel(graphics);

      }
    };
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(819, 511));
    setMinimumSize(new java.awt.Dimension(819, 511));

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    addNodeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addIcon.png"))); // NOI18N
    addNodeButton.setFocusable(false);
    addNodeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addNodeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addNodeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addNodeButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(addNodeButton);

    addEdgeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edgeIcon.png"))); // NOI18N
    addEdgeButton.setFocusable(false);
    addEdgeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addEdgeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addEdgeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addEdgeButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(addEdgeButton);
    jToolBar1.add(jSeparator1);

    getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane1.setOpaque(false);

    nodePanel.setBackground(new java.awt.Color(255, 255, 255));
    nodePanel.setMinimumSize(new java.awt.Dimension(500, 400));
    nodePanel.setLayout(null);
    jScrollPane1.setViewportView(nodePanel);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void addNodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNodeButtonActionPerformed
    incompleteNode = new Node();
    incompleteNode.setLocation(20, 20);
    nodePanel.add(incompleteNode);

    incompleteNode.addMouseListener(nodeMouseClicked);
    incompleteNode.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        if (incompleteEdge != null) {
          if (incompleteEdge.isEmpty()) {
            Node node = (Node) e.getSource();
            incompleteEdge.add(node);
          }
          else {
            Node A = incompleteEdge.getA();
            Node B = (Node) e.getSource();
            A.connect(B);
            B.connect(A);
            incompleteEdge = null;
          }
        }
      }
    });
  }//GEN-LAST:event_addNodeButtonActionPerformed

  private void addEdgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeButtonActionPerformed
    createEdge();
  }//GEN-LAST:event_addEdgeButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Simulation().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addEdgeButton;
  private javax.swing.JButton addNodeButton;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JPanel nodePanel;
  // End of variables declaration//GEN-END:variables

  private void createEdge() {
    incompleteEdge = new Edge();
  }

  public void refresh() {
    new Thread() {
      @Override
      public void run() {
        while (true) {
          try {
            nodePanel.repaint();
            sleep(1000 / 60);
          }
          catch (InterruptedException ex) {
            Logger.getLogger(Simulation.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
      }
    }.start();
  }

  public void paintNodePanel(Graphics2D graphics) {
    paintIncompleteLine(graphics);
    paintDirectConnections(graphics);
    
    

  }

  private void paintDirectConnections(Graphics2D graphics) {
    for (int i = 0; i < nodes.size(); i++) {
      Node origin = nodes.get(i);
      ArrayList<Node> connections = origin.getConnections();
      for (int j = 0; j < connections.size(); j++) {
        Node destination = connections.get(j);
        Point A = origin.getCenter();
        Point B = destination.getCenter();
        graphics.drawLine(A.x, A.y, B.x, B.y);
      }      
    }
  }
  
  public Node getNode(String name, Node node){
    final ArrayList<Node> list = node.getConnections();
    for (int i = 0; i < list.size(); i++) {
      if(name.equals(list.get(i).getRouter().getPort()+"")){
        return list.get(i);
      }      
    }
    return null;
  }

  private void paintIncompleteLine(Graphics2D graphics) throws HeadlessException {
    if (incompleteEdge != null && incompleteEdge.isIncomplete()) {
      Point center = incompleteEdge.getA().getCenter();
      Point panel = nodePanel.getLocationOnScreen();
      Point pointer = MouseInfo.getPointerInfo().getLocation();

      int x = pointer.x - panel.x;
      int y = pointer.y - panel.y;

      graphics.drawLine(center.x, center.y, x, y);
    }
  }
}
