/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author Yan Kaic
 */
public class Simulation extends javax.swing.JFrame {

  Node incompleteNode;

  /**
   * Creates new form Simulation
   */
  public Simulation() {
    initComponents();

    nodePanel.addMouseMotionListener(new MouseMotionListener() {
      @Override
      public void mouseDragged(MouseEvent e) {
      }

      @Override
      public void mouseMoved(MouseEvent e) {
        if (incompleteNode != null) {
          incompleteNode.moveMouse();
        }
      }
    }
    );
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    jScrollPane1 = new javax.swing.JScrollPane();
    nodePanel = new javax.swing.JPanel();
    node1 = new view.Node();
    node2 = new view.Node();
    node3 = new view.Node();
    node4 = new view.Node();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(819, 511));
    setMinimumSize(new java.awt.Dimension(819, 511));

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addIcon.png"))); // NOI18N
    jButton1.setFocusable(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jToolBar1.add(jButton1);

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edgeIcon.png"))); // NOI18N
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton2);
    jToolBar1.add(jSeparator1);

    getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane1.setOpaque(false);

    nodePanel.setBackground(new java.awt.Color(255, 255, 255));
    nodePanel.setMinimumSize(new java.awt.Dimension(500, 400));
    nodePanel.setLayout(null);

    node1.setBackground(new java.awt.Color(255, 0, 51));
    nodePanel.add(node1);
    node1.setBounds(128, 173, 45, 45);
    nodePanel.add(node2);
    node2.setBounds(219, 265, 45, 45);
    nodePanel.add(node3);
    node3.setBounds(233, 122, 45, 45);
    nodePanel.add(node4);
    node4.setBounds(44, 287, 45, 45);

    jScrollPane1.setViewportView(nodePanel);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    incompleteNode = new Node();
    incompleteNode.setLocation(20, 20);
    nodePanel.add(incompleteNode);

    incompleteNode.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        incompleteNode = null;
      }
    }
    );
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Simulation().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar jToolBar1;
  private view.Node node1;
  private view.Node node2;
  private view.Node node3;
  private view.Node node4;
  private javax.swing.JPanel nodePanel;
  // End of variables declaration//GEN-END:variables
}
